### PR TITLE
Fixes #28. Cannot use Catch node for Alchemy errors.

### LINKED ISSUE #28: Cannot catch "Feature Extract" node error
I am using the "Feature Extract" node and when I reach my daily limits I can see the following error in the logs:

OUT 8 Dec 14:17:38 - [error] [alchemy-feature-extract:12082910.edf7d7] Alchemy API request error: daily-transaction-limit-exceeded

But I don't catch this error in the Catch node. I believe the second argument (msg) is missing when sending this error with node.error function.

### PR DESCRIPTION
**Pull request by jthomas**
Adding error message as second parameter in node.error calls.

### CODE REVIEW

File: alchemy/feature-extract.js [hunk 1]
```diff
@@ -53,14 +53,16 @@ module.exports = function (RED) {
 
     this.on('input', function (msg) {
       if (!msg.payload) {
-        node.error('Missing property: msg.payload');
+        var message = 'Missing property: msg.payload';
+        node.error(message, message);
```
Comment (knolleary) [inline alchemy/feature-extract.js]: The second arg should be the `msg` object, not `message`

**Comment by jthomas** [comment]
Updated to use node.error() correctly.
